psql -U postgres -c "CREATE DATABASE uni;"
# create table
psql -U postgres -d uni -c "CREATE UNLOGGED TABLE Degrees(DegreeId INT PRIMARY KEY,Dept VARCHAR,DegreeDescription VARCHAR,TotalECTS INT);"
psql -U postgres -d uni -c "CREATE UNLOGGED TABLE Students(StudentId INT PRIMARY KEY,StudentName VARCHAR,Address VARCHAR,BirthyearStudent INT,Gender VARCHAR);"
psql -U postgres -d uni -c "CREATE UNLOGGED TABLE Teachers(TeacherId INT PRIMARY KEY,TeacherName VARCHAR,Address VARCHAR,BirthyearTeacher INT,Gender VARCHAR) ;"
psql -U postgres -d uni -c "CREATE UNLOGGED TABLE Courses(CourseId INT PRIMARY KEY,CourseName VARCHAR,CourseDescription VARCHAR,DegreeId INT ,ECTS INT);"
psql -U postgres -d uni -c "CREATE UNLOGGED TABLE CourseOffers(CourseOfferId INT PRIMARY KEY,CourseId INT, Year INT ,Quartile INT );"
psql -U postgres -d uni -c "CREATE UNLOGGED TABLE StudentRegistrationsToDegrees(StudentRegistrationId INT PRIMARY KEY,StudentId INT,DegreeId INT ,RegistrationYear INT );"
psql -U postgres -d uni -c "CREATE UNLOGGED TABLE CourseRegistrations(CourseOfferId INT,StudentRegistrationId INT ,Grade INT );"
psql -U postgres -d uni -c "CREATE UNLOGGED TABLE StudentAssistants(CourseOfferId INT,StudentRegistrationId INT );"
psql -U postgres -d uni -c "CREATE UNLOGGED TABLE TeacherAssignmentsToCourses(CourseOfferId INT ,TeacherId INT);"
#
# copy data
psql -U postgres -d uni -c "COPY CourseOffers(CourseOfferId,CourseId,Year,Quartile)  FROM '/mnt/ramdisk/tables/CourseOffers.table' DELIMITER ',' CSV HEADER;"
psql -U postgres -d uni -c "COPY CourseRegistrations(CourseOfferId,StudentRegistrationId,Grade)  FROM '/mnt/ramdisk/tables/CourseRegistrations.table' DELIMITER ',' CSV HEADER NULL 'null';"
psql -U postgres -d uni -c "COPY Courses(CourseId,CourseName,CourseDescription,DegreeId,ECTS)  FROM '/mnt/ramdisk/tables/Courses.table' DELIMITER ',' CSV HEADER;"
psql -U postgres -d uni -c "COPY Degrees(DegreeId,Dept,DegreeDescription,TotalECTS)  FROM '/mnt/ramdisk/tables/Degrees.table' DELIMITER ',' CSV HEADER;"
psql -U postgres -d uni -c "COPY StudentAssistants(CourseOfferId,StudentRegistrationId)  FROM '/mnt/ramdisk/tables/StudentAssistants.table' DELIMITER ',' CSV HEADER;"
psql -U postgres -d uni -c "COPY StudentRegistrationsToDegrees(StudentRegistrationId,StudentId,DegreeId,RegistrationYear)  FROM '/mnt/ramdisk/tables/StudentRegistrationsToDegrees.table' DELIMITER ',' CSV HEADER;"
psql -U postgres -d uni -c "COPY Students(StudentId,StudentName,Address,BirthyearStudent,Gender)  FROM '/mnt/ramdisk/tables/Students.table' DELIMITER ',' CSV HEADER;"
psql -U postgres -d uni -c "COPY TeacherAssignmentsToCourses(CourseOfferId,TeacherId)  FROM '/mnt/ramdisk/tables/TeacherAssignmentsToCourses.table' DELIMITER ',' CSV HEADER;"
psql -U postgres -d uni -c "COPY Teachers(TeacherId,TeacherName,Address,BirthyearTeacher,Gender)  FROM '/mnt/ramdisk/tables/Teachers.table' DELIMITER ',' CSV HEADER;"
psql -U postgres -d uni -c "VACUUM;"
psql -U postgres -d uni -c "ANALYZE;"
#
#
# loading CourseRegistrations to small tables
psql -U postgres -d uni -c "CREATE UNLOGGED TABLE CourseRegistrations_NULL AS SELECT * FROM CourseRegistrations WHERE NOT (CourseRegistrations.grade IS NOT NULL) ORDER BY studentregistrationid;"
psql -U postgres -d uni -c "CREATE UNLOGGED TABLE CourseRegistrations_failed AS SELECT * FROM CourseRegistrations WHERE grade < 4 ORDER BY studentregistrationid;"
psql -U postgres -d uni -c "CREATE UNLOGGED TABLE CourseRegistrations_4 AS SELECT * FROM CourseRegistrations WHERE grade = 4 ORDER BY studentregistrationid;"
psql -U postgres -d uni -c "CREATE UNLOGGED TABLE CourseRegistrations_passed AS SELECT * FROM CourseRegistrations WHERE grade >4 ORDER BY studentregistrationid;"
psql -U postgres -d uni -c "DROP TABLE CourseRegistrations;"
psql -U postgres -d uni -c "ALTER TABLE courseregistrations_4 ADD PRIMARY KEY (studentregistrationid,courseofferid);"
psql -U postgres -d uni -c "ALTER TABLE courseregistrations_null ADD PRIMARY KEY (studentregistrationid,courseofferid);"
psql -U postgres -d uni -c "ALTER TABLE courseregistrations_failed ADD PRIMARY KEY (studentregistrationid,courseofferid);"
psql -U postgres -d uni -c "ALTER TABLE courseregistrations_passed ADD PRIMARY KEY (studentregistrationid,courseofferid);"
