SELECT	Courses.CourseName,CourseRegistrations_passed.Grade FROM Students, Degrees, StudentRegistrationsToDegrees,CourseRegistrations_passed,CourseOffers,Courses WHERE Students.StudentID = %1% AND Degrees.DegreeId = %2% AND StudentRegistrationsToDegrees.studentID = students.studentID AND	StudentRegistrationsToDegrees.DegreeId = Degrees.DegreeId AND CourseRegistrations_passed.StudentRegistrationId = StudentRegistrationsToDegrees.StudentRegistrationId AND CourseRegistrations_passed.CourseOfferId = CourseOffers.CourseOfferId AND Courses.CourseId = CourseOffers.CourseId ORDER BY CourseOffers.year, CourseOffers.quartile;
SELECT 0;
SELECT 0;
SELECT CAST((SELECT COUNT(*) FROM students, degrees, studentregistrationstodegrees WHERE students.gender = 'F' AND degrees.dept = %1% AND studentregistrationstodegrees.DegreeId = degrees.DegreeId AND studentregistrationstodegrees.StudentId = students.StudentId) AS FLOAT) / CAST((SELECT COUNT(*) FROM students, degrees, studentregistrationstodegrees WHERE degrees.dept = %1% AND studentregistrationstodegrees.DegreeId = degrees.DegreeId AND studentregistrationstodegrees.StudentId = students.StudentId) AS FLOAT);
SELECT 0;
SELECT count_good_student.sid AS studentid, count(count_good_student.good_times) filter (where count_good_student.good_times >= 2) AS numberOfCoursesWhereExcellent FROM ( SELECT good_student.sid,	count(good_student.good_grades) as good_times FROM good_student GROUP BY good_student.sid ) AS count_good_student GROUP BY studentid;
SELECT 0;
SELECT C.CourseName, CO.Year, CO.Quartile FROM Courses as C, CourseOffers as CO, (SELECT S.courseOfferID FROM students_per_courseoffer as S, assistants_per_courseOffer as A WHERE S.courseOfferID = A.courseOfferID AND S.students/A.assistants > 50) as L WHERE L.CourseOfferId = CO.CourseOfferId and C.CourseID = CO.CourseID ORDER BY CO.Courseofferid;

